---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/tautulli/config:/config
      - /opt/plex/config:/plexconfig
    ports:
      - 8181:8181
    restart: unless-stopped