---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/radarr/config:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    restart: unless-stopped